### ISSUE TITLE
Failed to execute 'appendChild' on 'Node': The new child element contains the parent.

### ISSUE THREAD

**Issue by kontrollanten** [prateekbh/preact-async-ssr#1]
Thanks for the sample application! I tried to run it as described in the README, but I get the following when I run the application

```
Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
```

Which points to 

```
	// append the element if its a new parent
	if (parent && ret.parentNode !== parent) parent.appendChild(ret);
```

in client.js.

**Comment by prateekbh** [comment]
Thanks for reporting!

fixed it in : https://github.com/prateekbh/preact-async-ssr/commit/eb77d0c54d0fe6424ef97485621cf85a4fe1aabf
